project:
  type: book
  output-dir: _book

book:
  title: "Data"
  author: "Julio Toboso"
  chapters:
    - index.qmd
    - part: "Sample Space"
      chapters:
        - sample-space/index.qmd
        - sample-space/maps-and-reality.qmd
        - sample-space/randomness-and-pattern.qmd
        - sample-space/outcomes-and-events.qmd
        - sample-space/finite-and-infinite.qmd
        - sample-space/kolmogorov.qmd     
    
format:
  html:
    theme: lux
    code-copy: true
    code-fold: show

execute:
  execute-notebooks: auto
